"""add

Revision ID: 04f1d6d29f2f
Revises: a8eb0c97dbc1
Create Date: 2025-04-16 14:08:07.036968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f1d6d29f2f'
down_revision = 'a8eb0c97dbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
