"""add

Revision ID: 0a89731fb270
Revises: 04f1d6d29f2f
Create Date: 2025-04-16 18:14:17.796233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a89731fb270'
down_revision = '04f1d6d29f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
